---
- hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - nginx
          - nodejs
          - npm
          - git
        state: present
        update_cache: yes

    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Source nvm in .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "source {{ ansible_env.HOME }}/.nvm/nvm.sh"
        create: yes

    - name: Instal and set Node.js 16
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 16 && nvm use 16
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v16"

    - name: Create projects directory
      file:
        path: "{{ ansible_env.HOME }}/projects"
        state: directory

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Set NODE_OPTIONS environment variable
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "export NODE_OPTIONS=--max-old-space-size=8192"
        create: yes

    - name: Run database migrations
      shell: . ~/.nvm/nvm.sh && npx sequelize db:migrate
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}/projects"
      become: false

    - name: Run database seeders
      shell: . ~/.nvm/nvm.sh && npx sequelize db:seed -seed arquivo-da-seeder.js
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}/projects/pasta-back"
      become: false

    - name: Restart application with PM2
      shell: . ~/.nvm/nvm.sh && pm2 restart app.js
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}/projects"
      become: false
