---
- name: Deploy application
  hosts: all
  become: true

  tasks:
    - name: Start MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Check if HTTP ports are open in UFW
      command: ufw status
      register: ufw_status
      changed_when: false

    - name: Allow HTTP port 80
      command: ufw allow 80
      when: '"80" not in ufw_status.stdout'

    - name: Allow HTTPS port 443
      command: ufw allow 443
      when: '"443" not in ufw_status.stdout'

    - name: Change to projects directory
      command: cd projects
      args:
        chdir: "{{ ansible_env.HOME }}"

    - name: Set Node.js version using NVM
      shell: . ~/.nvm/nvm.sh && nvm use 16
      args:
        executable: /bin/bash
      become: false

    - name: Start application with PM2
      shell: . ~/.nvm/nvm.sh && pm2 start app.js
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}/projects"
      become: false

    - name: Check server IP
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        return_content: yes
      register: instance_ip
      ignore_errors: true

    - name: Display IP check message
      debug:
        msg: "Please check if IP {{ instance_ip.content }} matches DNS records in Locaweb platform"
      when: instance_ip is success
