---
- name: Deploy application
  hosts: vlab-local
  become: true
  become_exe: sudo -s
  become_user: root
  become_method: sudo
  vars:
    ansible_become_pass: 654321
  roles:
    - k3s-containers-setup
    - k3s-nginx
    - databases