---
- name: Create working directory
  file:
    path: /opt/database
    state: directory
    mode: '0755'


- name: copy docker-compose.yaml file to remote host
  copy:
    src: files/docker-compose.yaml
    dest: /opt/database/docker-compose.yaml
    mode: '0600'

- name: Apply docker-compose.yaml file
  community.docker.docker_compose_v2:
    project_src: /opt/database
    state: present