---
- include_tasks: "containers-setup.yaml"

- name: Copy dumps file to remote host
  copy:
    src: files/{{item}}.dump
    dest: ./{{item}}.dump
    mode: '0600'
  loop:
  - "cmr"
  - "inovaula"
  - "bq"

- name: Copy dumps file to the container
  community.docker.docker_container_copy_into:
    path: ./{{item}}.dump
    container_path: /{{item}}.dump
    container: postgres-{{item}}
    mode: '0600'
  loop:
    - "cmr"
    - "inovaula"
    - "bq"

- name: Apply dumps file into the container
  community.docker.docker_container_exec:
    container: postgres-{{item.name}}
    command: pg_restore -U {{item.user}} -d {{item.database}} /{{item.name}}.dump
    chdir: /
  loop:
    - { name: cmr, user: inovaula, database: cmr_inovaula }
    - { name: inovaula, user: inovaula, database: inovaula }
    - { name: bq, user: inovaula, database: inovaula }
