---
- name: Create dumps directory
  file:
    path: "./dumps"
    state: directory

- name: Copy dumps file to remote host
  copy:
    src: files/{{item}}.dump
    dest: ./dumps/{{item}}.dump
    mode: '0600'
  loop:
  - "inovaula"
  - "cmr"
  - "bq"

- name: setup namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ namespace }}
    kubeconfig: /opt/compose/kubeconfig.yaml

- include_tasks: setup-SVC-file.yaml
- include_tasks: setup-SVC.yaml
- include_tasks: setup-Operator.yaml
