---
- hosts: master
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      ignore_errors: true

    - name: Set up kubectl for the current user
      command: "{{ item }}"
      with_items:
        - "mkdir -p $HOME/.kube"
        - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "chown $(id -u):$(id -g) $HOME/.kube/config"

    - name: Install Calico network plugin
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: "'calico' in kubeadm_output.stdout"

- hosts: workers
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Join worker nodes to the cluster
      command: "{{ hostvars['master']['kubeadm_output']['stdout_lines'][0] }}"
      when: "'kubeadm join' in hostvars['master']['kubeadm_output']['stdout']"