---
- name: Undeploy containers with docker-compose
  community.docker.docker_compose_v2:
    project_src: /opt/{{ item }}
    state: absent
  loop:
    - compose
    - database

- name: removimg docker volumes
  docker_volume:
    name: 
    state: absent
  loop:
    - postgres_bq_data__
    - postgres_inovaula_data__
    - postgres_cmr_data__