name: Deploy to PROD

on:
  workflow_dispatch:
    inputs:
      service:
        required: false
        description: Service that will be deployed
        default: "api"
      tag:
        required: true
        description: service tag version
env:
  AWS_REGION:
  CLUSTER_NAME:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update version in deployment
        run: sed -i -- 's/latest/${{ github.event.inputs.tag }}/g' api/${{ github.event.inputs.service }}-deployment.yaml

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{env.CLUSTER_NAME}} --region ${{env.AWS_REGION}}

      - name: Apply secrets
        run: kubectl apply -f api/${{ github.event.inputs.service }}-secret.yaml

      - name: Apply configmaps
        run: kubectl apply -f api/${{ github.event.inputs.service }}-configmap.yaml

      - name: Deploy changes into cluster
        run: kubectl apply -f api/${{ github.event.inputs.service }}-deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/api
