apiVersion: v1

kind: Secret

metadata:
  name: api-secrets

type: Opaque

stringData:
  MONGODB_URL: "mongodb+srv://root:admin@cluster0.hk16k9u.mongodb.net/tangramqa?retryWrites=true&w=majority"
  POSTGRES_URL: "postgresql://postgres:tangramgame2020@tangramapiqa.cxbcoravi8jc.sa-east-1.rds.amazonaws.com/tangramqa?schema=public"

  
 
