---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Get Kubernetes package key
  shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
  args:
    creates: "{{ k8s_gpgpath }}"

- name: Install Kubernetes repository
  apt_repository:
    repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"
    filename: kubernetes
    state: present
    update_cache: true

- name: Install kubectl and python dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubectl
    - python3-kubernetes

