apiVersion: apps/v1

kind: Deployment

metadata:
  name: api
  labels:
    app: api

spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: main-sa
      containers:
        - name: api
          image: ECR_IMAGE
          resources:
            limits:
              cpu: "Vm"
            requests:
              cpu: "Vm"
          ports:
            - containerPort:
          envFrom:
            - configMapRef:
                name: api-configmap
            - secretRef:
                name: api-secrets
